require("../string")

--[[[
    Get a numeric representation of the character at the index of the given
    string.

    Gets the first character of the given string if no index is provided.

    @param {string} str The target string.
    @param {number|nil} [index=1] The index of the target character.

    @returns {number|nil} The character code or nil if the index is out of
        range.
]]
string.byte = function(str, index)
end
