comment:
  layout: "diff, files"
  behavior: default
  require_changes: no

coverage:
  range: 80..100
  round: down
  precision: 2

  status:
    project:
      default:
        target: 90%
        threshold: 2%
    patch: yes
    changes: no
