language: node_js
branches:
  # only master, dev, and tagged commits
  only:
  - master
  - dev
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
node_js:
- "node"
- "lts/*"
install:
- npm install --devDependencies
before_script:
- npm run compile
script:
- npm run lint
- npm run test:coverage
cache:
  directories:
  - "node_modules"
