#!/usr/bin/env node
var fs = require("fs");
var path = require("path");
var process = require("process");

(new Map([
    ["../.antlr/TspLexer.js", "../src/TspLexer.generated.js"],
    ["../.antlr/TspParser.js", "../src/TspParser.generated.js"],
    ["../.antlr/TspListener.js", "../src/TspListener.generated.js"],
    ["../.antlr/TspVisitor.js", "../src/TspVisitor.generated.js"],
])).forEach((dest, src) => {
    if (fs.existsSync(src)) {
        try {
            fs.renameSync(src, dest);
        } catch (e) {
            console.error(e)
        }
    } else {
        console.log(
            `${path.basename(process.argv[1])}: skipping non-existent file @ ${path.resolve(src)}`
        );
    }
});

