--[[[
    @deprecated

    @deprecated Mauris scelerisque nibh libero.

    ---

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus posuere
    sem urna, vel placerat odio mattis vitae. Cras ac pellentesque lorem, in
    commodo ex. Suspendisse et ultrices ligula, eget laoreet nibh.

    @desc Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
    posuere sem urna, vel placerat odio mattis vitae. Cras ac pellentesque
    lorem, in commodo ex. Suspendisse et ultrices ligula, eget laoreet nibh.

    @description Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Vivamus posuere sem urna, vel placerat odio mattis vitae. Cras ac
    pellentesque lorem, in commodo ex. Suspendisse et ultrices ligula, eget
    laoreet nibh.

    ---

    @param {type} lowercase Sed eget turpis venenatis leo maximus mattis.

    @parameter {
        nil|
        buffer.UNIT_AMP
        |table
    } camelCase Sed eget turpis venenatis leo maximus mattis.

    @param {
        function(userdata) => any
    } snake_case Sed eget turpis venenatis leo maximus mattis.

    @parameter lowercase Sed eget turpis venenatis leo maximus mattis.

    @param [PascalCase="\"double (\")\" quoted"] Sed eget turpis venenatis leo
        maximus mattis.

    @parameter [camelCase='\'single (\')\' quoted'] Sed eget turpis venenatis leo
        maximus mattis.

    @param [snake_case=smu.FUNC_DC_VOLTAGE] Sed eget turpis venenatis leo
        maximus mattis.

    @parameter sArCaStIcCaSe Sed eget turpis venenatis leo maximus mattis.

    @param InVeRsEsArCaStIcCaSe Sed eget turpis venenatis leo maximus mattis.

    ---

    @return {type} Quisque fringilla est.

    @returns {
        nil|
        buffer.UNIT_AMP
        |table
    } Quisque fringilla est.

    @return {
        function( userdata ) => any
    } Quisque fringilla est.

    @returns Quisque fringilla est.

    @return Quisque fringilla est.

    ---

    @see my.table.field:syntacticSugar is not highlighted!

    @see MyType$ only valid TSP variable characters are highlighted!

    @see https://www.github.com/tektronix for the official Tektronix GitHub
        Organization.

    @see {@link https://www.github.com/tektronix/vscode-tsplang
            |vscode-tsplang} is this project's homepage.

    @see {@link beeper.beep}

    ---

    @tsplink

    @tsplink Nullam id risus ex.

    ---

    @typedef smu.measure.math.mxb.bfactor:syntacticSugar is not highlighted!

    @typedef MyNewType[] only valid TSP variable characters are highlighted!

    @typedef {
        buffer.DIGIT_3_5
        |buffer.DIGIT_4_5
        |buffer.DIGIT_5_5
        |buffer.DIGIT_6_5
        |buffer.DIGIT_7_5
        |buffer.DIGIT_8_5
    } BufferDigits&& only valid TSP variable characters are highlighted!

    ---

    @field {type} lowercase Sed eget turpis venenatis leo maximus mattis.

    @field {
        nil|
        buffer.UNIT_AMP
        |table
    } camelCase Sed eget turpis venenatis leo maximus mattis.

    @field {
        function( userdata ) => any
    } snake_case Sed eget turpis venenatis leo maximus mattis.

    @field [lowercase=] Sed eget turpis venenatis leo maximus mattis.

    @field [PascalCase="\"double\" quoted"] Sed eget turpis venenatis leo
        maximus mattis.

    @field [camelCase='\'single\' quoted'] Sed eget turpis venenatis leo
        maximus mattis.

    @field [snake_case=smu.FUNC_DC_VOLTAGE] Sed eget turpis venenatis leo
        maximus mattis.

    @field sArCaStIcCaSe Sed eget turpis venenatis leo maximus mattis.

    ---

    @index {type} Quisque fringilla est.

    @index {
        nil|
        buffer.UNIT_AMP
        |table
    } Quisque fringilla est.

    @index {
        function( userdata ) => any
    } Quisque fringilla est.

    @index Quisque fringilla est.

    @index Quisque fringilla est.

    ---

    @readonly

    @readonly Nullam id risus ex.

    @readOnly

    @readOnly Nullam id risus ex.

    ---

    @writeonly

    @writeonly Nullam id risus ex.

    @writeOnly

    @writeOnly Nullam id risus ex.

    ---

    @const

    @const Nullam id risus ex.

    @constant

    @constant Nullam id risus ex.

    ---

    @type {type} Quisque fringilla est.

    @type {
        nil|
        buffer.UNIT_AMP
        |table
    } Quisque fringilla est.

    @type {
        function( userdata ) => any
    } Quisque fringilla est.

    @type Quisque fringilla est.

    ---

    @fw >0.0.0, <=1.0.0, ==2.0.0

    @firmware >0.0.0, <=1.0.0, ==2.0.0

    ---

    @tsp-v1

    @tsp-v1 Nullam id risus ex.

    ---

    @tsp-v2

    @tsp-v2 Nullam id risus ex.

    ---

    @v1 smu.measure.math.mxb.mfactor:syntacticSugar is not hightlighted!

    @v1 TypeAlias* only valid TSP variable characters are highlighted!

    ---

    @v2 smu.measure.math.percent:syntacticSugar is not hightlighted!

    @v2 TypeAlias) only valid TSP variable characters are highlighted!

    ---
]]
