--[[[
    @deprecated

    @deprecated Mauris scelerisque nibh libero.

    ---

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus posuere
    sem urna, vel placerat odio mattis vitae. Cras ac pellentesque lorem, in
    commodo ex. Suspendisse et ultrices ligula, eget laoreet nibh.

    @desc Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
    posuere sem urna, vel placerat odio mattis vitae. Cras ac pellentesque
    lorem, in commodo ex. Suspendisse et ultrices ligula, eget laoreet nibh.

    @description Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Vivamus posuere sem urna, vel placerat odio mattis vitae. Cras ac
    pellentesque lorem, in commodo ex. Suspendisse et ultrices ligula, eget
    laoreet nibh.

    ---

    @param {type} lowercase Sed eget turpis venenatis leo maximus mattis.

    @parameter {function} PascalCase Sed eget turpis venenatis leo maximus
        mattis.

    @param {
        nil|
        buffer.UNIT_AMP
        |table?
    } camelCase Sed eget turpis venenatis leo maximus mattis.

    @parameter {
        function(userdata?) => any
    } snake_case Sed eget turpis venenatis leo maximus mattis.

    @param [lowercase=] Sed eget turpis venenatis leo maximus mattis.

    @parameter [PascalCase="\"double\" quoted"] Sed eget turpis venenatis leo
        maximus mattis.

    @param [camelCase='\'single\' quoted'] Sed eget turpis venenatis leo
        maximus mattis.

    @parameter [snake_case=smu.FUNC_DC_VOLTAGE] Sed eget turpis venenatis leo
        maximus mattis.

    @param sArCaStIcCaSe Sed eget turpis venenatis leo maximus mattis.

    @parameter InVeRsEsArCaStIcCaSe Sed eget turpis venenatis leo maximus mattis.

    ---

    @return {type} Quisque fringilla est.

    @returns {{table;
                userdata,}} Quisque fringilla est.

    @return {(
        smu.FUNC_DC_CURRENT,
        thread,
    )} Quisque fringilla est.

    @returns {
        function( ({this, could}, be, any) ) => any
    } Quisque fringilla est.

    @return Quisque fringilla est.

    @returns Quisque fringilla est.

    ---

    @see smu.measure.math.mxb.bfactor:syntacticSugar is not highlighted!

    @see MyType$ only valid TSP variable characters are highlighted!

    @see https://www.github.com/tektronix for the official Tektronix GitHub
        Organization.

    @see {@link https://www.github.com/tektronix/vscode-tsplang
            |vscode-tsplang} is this project's homepage.

    @see {@link beeper.beep}

    ---

    @tsplink

    ---

    @typedef smu.measure.math.mxb.bfactor:syntacticSugar is not highlighted!

    @typedef MyNewType[] only valid TSP variable characters are highlighted!

    @typedef {(
        buffer.DIGIT_3_5,
        buffer.DIGIT_4_5,
        buffer.DIGIT_5_5,
        buffer.DIGIT_6_5,
        buffer.DIGIT_7_5,
        buffer.DIGIT_8_5,
    )} BufferDigits&& only valid TSP variable characters are highlighted!

    ---

    @field {type} lowercase Sed eget turpis venenatis leo maximus mattis.

    @field {{string;
             number,}} PascalCase Sed eget turpis venenatis leo maximus
        mattis.

    @field {(
        nil,
        buffer.UNIT_AMP
    )} camelCase Sed eget turpis venenatis leo maximus mattis.

    @field {
        function({ infinite, {recursion} }) => any
    } snake_case Sed eget turpis venenatis leo maximus mattis.

    @field [lowercase=] Sed eget turpis venenatis leo maximus mattis.

    @field [PascalCase="\"double\" quoted"] Sed eget turpis venenatis leo
        maximus mattis.

    @field [camelCase='\'single\' quoted'] Sed eget turpis venenatis leo
        maximus mattis.

    @field [snake_case=smu.FUNC_DC_VOLTAGE] Sed eget turpis venenatis leo
        maximus mattis.

    @field sArCaStIcCaSe Sed eget turpis venenatis leo maximus mattis.

    ---

    @readonly

    @readOnly

    ---

    @writeonly

    @writeOnly

    ---

    @const

    @constant

    ---

    @type {type} Quisque fringilla est.

    @type {{table;
            userdata,}} Quisque fringilla est.

    @type {(
        smu.FUNC_DC_CURRENT,
        thread,
    )} Quisque fringilla est.

    @type {
        function( ({this, could}, be, any) ) => any
    } Quisque fringilla est.

    @type Quisque fringilla est.

    ---

    @fw >0.0.0, <=1.0.0, ==2.0.0

    ---

    @tsp-v1

    ---

    @tsp-v2

    ---

    @v1 smu.measure.math.mxb.mfactor:syntacticSugar is not hightlighted!

    @v1 TypeAlias* only valid TSP variable characters are highlighted!

    ---

    @v2 smu.measure.math.percent:syntacticSugar is not hightlighted!

    @v2 TypeAlias) only valid TSP variable characters are highlighted!

    ---
]]
