name: Code Extention CI

on:
  push:
    branches:
      - '**'
    tags:
      - v*
  pull_request:
    branches:
      - 'master'
      - 'dev'

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10.x, 12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          npm ci --ignore-scripts
          cd client
          npm ci
          cd ..
          cd server
          npm ci --ignore-scripts
          cd @antlr4-tsplang
          npm ci --ignore-scripts
          # cd ../@tsplang-plugins
          # npm ci --ignore-scripts
          cd ../..
        env:
          CI: true

      - name: build
        run: |
          npm run compile
        env:
          CI: true

      - name: style
        run: |
          npm run lint
        env:
          CI: true

      - name: test
        run: |
          npm run cover
        env:
          CI: true

      - name: Action Debugging
        env:
          GITHUB_REF: ${{ github.ref }}
          RUNNER_OS: ${{ runner.os }} 
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: echo "Ref - $GITHUB_REF | Runner - $RUNNER_OS | Event Name - $GITHUB_EVENT_NAME"

      - name: coverage export
        if: runner.os == 'Linux' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/bugfix/esarver-codecov-action' || github.event_name == 'pull_request')
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV }}
          yml: ./codecov.yml
          file: ./coverage/lcov.info
          # file?
        env:
          CI: true

      # - name: create package
      #   if: false
      #   run: |
      #     npm run package # TODO we need vsce for this
      #   env:
      #     CI: true

      # - name: export package
      #   if: false
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: vscode-tsplang
      #     path: vscode-tsplang*.vsix

